language: php
php:
    - '7.0'

before_script:
    - composer install
    - ./vendor/bin/codecept build

cache:
    directories:
        - ./vendor
        - ./$HOME/.composer/cache

branches:
    only:
        - master

script:
    - php vendor/bin/codecept run
